import * as Contexts from '../contexts'
import * as Attachments from '../common/attachments'

// @autogenerated generate-types-contexts-mapping-interface start
export interface ContextsMapping {
  callback_query: Contexts.CallbackQueryContext
  channel_chat_created: Contexts.ChannelChatCreatedContext
  chosen_inline_result: Contexts.ChosenInlineResultContext
  delete_chat_photo: Contexts.DeleteChatPhotoContext
  group_chat_created: Contexts.GroupChatCreatedContext
  inline_query: Contexts.InlineQueryContext
  invoice: Contexts.InvoiceContext
  left_chat_member: Contexts.LeftChatMemberContext
  message: Contexts.MessageContext
  edited_message: Contexts.MessageContext
  channel_post: Contexts.MessageContext
  edited_channel_post: Contexts.MessageContext
  migrate_to_chat_id: Contexts.MigrateToChatIdContext
  migrate_from_chat_id: Contexts.MigrateFromChatIdContext
  new_chat_members: Contexts.NewChatMembersContext
  new_chat_photo: Contexts.NewChatPhotoContext
  new_chat_title: Contexts.NewChatTitleContext
  pinned_message: Contexts.PinnedMessageContext
  poll: Contexts.PollContext
  poll_answer: Contexts.PollAnswerContext
  chat_member: Contexts.ChatMemberContext
  my_chat_member: Contexts.ChatMemberContext
  pre_checkout_query: Contexts.PreCheckoutQueryContext
  shipping_query: Contexts.ShippingQueryContext
  successful_payment: Contexts.SuccessfulPaymentContext
  supergroup_chat_created: Contexts.SupergroupChatCreatedContext
  message_auto_delete_timer_changed: Contexts.MessageAutoDeleteTimerChangedContext
  video_chat_scheduled: Contexts.VideoChatScheduledContext
  video_chat_started: Contexts.VideoChatStartedContext
  video_chat_ended: Contexts.VideoChatEndedContext
  video_chat_participants_invited: Contexts.VideoChatParticipantsInvitedContext
  web_app_data: Contexts.WebAppDataContext
  chat_join_request: Contexts.ChatJoinRequestContext
  proximity_alert_triggered: Contexts.ProximityAlertTriggeredContext
  passport_data: Contexts.PassportDataContext
  service_message: Contexts.MessageContext

  [key: string]: Contexts.Context
}
// @autogenerated generate-types-contexts-mapping-interface end

// @autogenerated generate-types-attachments-mapping-interface start
export interface AttachmentsMapping {
  animation: Attachments.AnimationAttachment
  audio: Attachments.AudioAttachment
  contact: Attachments.ContactAttachment
  document: Attachments.DocumentAttachment
  location: Attachments.LocationAttachment
  photo: Attachments.PhotoAttachment
  poll: Attachments.PollAttachment
  sticker: Attachments.StickerAttachment
  venue: Attachments.VenueAttachment
  video_note: Attachments.VideoNoteAttachment
  video: Attachments.VideoAttachment
  voice: Attachments.VoiceAttachment
}
// @autogenerated generate-types-attachments-mapping-interface end
