import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

import { UpdateType } from '../../packages/puregram/src'

const TYPES_PATH = resolve(__dirname, '..', '..', 'packages', 'puregram', 'src', 'types', 'types.ts')

const getContext = (key: string, value: string) => {
  if (['edited_message', 'channel_post', 'edited_channel_post'].includes(value)) {
    return 'MessageContext'
  }

  if (value === 'my_chat_member') {
    return 'ChatMemberContext'
  }

  if (value === 'service_message') {
    return 'MessageContext'
  }

  return `${key}Context`
}

const main = async () => {
  let typesTsContent = await readFile(TYPES_PATH, 'utf8')

  // INFO: generate-types-contexts-interface
  {
    const clauses: string[] = []

    // message: Contexts.MessageContext
    for (const [key, value] of Object.entries(UpdateType)) {
      clauses.push(`${value}: Contexts.${getContext(key, value)}`)
    }

    clauses.push('', '[key: string]: Contexts.Context')

    const RawEvents = `interface ContextsCollection {\n${clauses.map(clause => `  ${clause}`).join('\n')}\n}`
    const content = `// @autogenerated generate-types-contexts-interface start\n${RawEvents}\n// @autogenerated generate-types-contexts-interface end`

    typesTsContent = typesTsContent.replace(/\/\/\s@autogenerated\sgenerate-types-contexts-interface\sstart\n(.*)\n\/\/\s@autogenerated\sgenerate-types-contexts-interface\send/is, content)

    console.log('[generate-types-contexts-interface] successfully generated `ContextsCollection` interface')
  }

  await writeFile(TYPES_PATH, typesTsContent)
}

main().catch(console.error)
