import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

import { AttachmentType, UpdateType } from '../../packages/puregram/src'

const MAPPINGS_PATH = resolve(__dirname, '..', '..', 'packages', 'puregram', 'src', 'types', 'mappings.ts')

const getContext = (key: string, value: string) => {
  if (['edited_message', 'channel_post', 'edited_channel_post'].includes(value)) {
    return 'MessageContext'
  }

  if (value === 'my_chat_member') {
    return 'ChatMemberContext'
  }

  if (value === 'service_message') {
    return 'MessageContext'
  }

  return `${key}Context`
}

const main = async () => {
  let mappingsTsContent = await readFile(MAPPINGS_PATH, 'utf8')

  // INFO: generate-types-contexts-mapping-interface
  {
    const clauses: string[] = []

    // message: Contexts.MessageContext
    for (const [key, value] of Object.entries(UpdateType)) {
      clauses.push(`${value}: Contexts.${getContext(key, value)}`)
    }

    clauses.push('', '[key: string]: Contexts.Context')

    const RawMappings = `export interface ContextsMapping {\n${clauses.map(clause => `  ${clause}`).join('\n')}\n}`
    const content = `// @autogenerated generate-types-contexts-mapping-interface start\n${RawMappings}\n// @autogenerated generate-types-contexts-mapping-interface end`

    mappingsTsContent = mappingsTsContent.replace(/\/\/\s@autogenerated\sgenerate-types-contexts-mapping-interface\sstart\n(.*)\n?\/\/\s@autogenerated\sgenerate-types-contexts-mapping-interface\send/is, content)

    console.log('[generate-types-contexts-mapping-interface] successfully generated `ContextsMapping` interface')
  }

  // INFO: generate-types-attachments-mapping-interfaces
  {
    const clauses: string[] = []

    // photo: PhotoAttachment
    for (const [key, value] of Object.entries(AttachmentType)) {
      clauses.push(`${value}: Attachments.${key}Attachment`)
    }

    const RawMappings = `export interface AttachmentsMapping {\n${clauses.map(clause => `  ${clause}`).join('\n')}\n}`
    const content = `// @autogenerated generate-types-attachments-mapping-interface start\n${RawMappings}\n// @autogenerated generate-types-attachments-mapping-interface end`

    mappingsTsContent = mappingsTsContent.replace(/\/\/\s@autogenerated\sgenerate-types-attachments-mapping-interface\sstart\n(.*)\n?\/\/\s@autogenerated\sgenerate-types-attachments-mapping-interface\send/is, content)

    console.log('[generate-types-attachments-mapping-interface] successfully generated `AttachmentsMapping` interface')
  }

  await writeFile(MAPPINGS_PATH, mappingsTsContent)
}

main().catch(console.error)
