// emit-augmentations.ts — codegen for src/generated/augmentations.ts
//
// reads @puregram/api/src/generated/updates.ts, extracts the UpdateKindMap entries,
// filters by the SESSION_AUGMENTED_KINDS curated whitelist, and emits one
// `declare module '@puregram/api' { interface XUpdate { session: SessionContext } }`
// block per kind. run via `yarn generate:augmentations` after a @puregram/api
// version bump (or whenever new update kinds with addressable users/chats land).
//
// the curated whitelist is the source of truth for "which kinds get a session
// attached at runtime". keep it in sync with `src/session.ts`'s defaultGetStorageKey
// — every kind in the whitelist must have at least one of from / senderChat / chat.

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const UPDATES_PATH = resolve(here, '../../api/src/generated/updates.ts')
const OUT_PATH = resolve(here, '../src/generated/augmentations.ts')

// kinds whose default getStorageKey can return a non-undefined value (have at
// least one of from / senderChat / chat). excluded by design: poll, message_reaction_count.
const SESSION_AUGMENTED_KINDS = new Set<string>([
  'message',
  'edited_message',
  'channel_post',
  'edited_channel_post',
  'business_connection',
  'business_message',
  'edited_business_message',
  'deleted_business_messages',
  'message_reaction',
  'callback_query',
  'inline_query',
  'chosen_inline_result',
  'shipping_query',
  'pre_checkout_query',
  'poll_answer',
  'my_chat_member',
  'chat_member',
  'chat_join_request',
  'chat_boost',
  'removed_chat_boost',
  'new_chat_members',
  'left_chat_member',
  'new_chat_title',
  'new_chat_photo',
  'delete_chat_photo',
  'group_chat_created',
  'pinned_message',
  'invoice',
  'successful_payment',
  'users_shared',
  'chat_shared',
  'web_app_data',
  'video_chat_scheduled',
  'video_chat_started',
  'video_chat_ended',
  'video_chat_participants_invited',
  'forum_topic_created',
  'forum_topic_edited',
  'forum_topic_closed',
  'forum_topic_reopened',
  'general_forum_topic_hidden',
  'general_forum_topic_unhidden',
  'giveaway_created',
  'giveaway_completed',
  'giveaway_winners',
  'boost_added',
  'message_auto_delete_timer_changed',
  'migrate_to_chat_id',
  'migrate_from_chat_id',
  'passport_data',
  'proximity_alert_triggered',
  'write_access_allowed'
])

const text = await readFile(UPDATES_PATH, 'utf8')

const mapMatch = /export interface UpdateKindMap \{([\s\S]*?)\}/.exec(text)

if (!mapMatch) {
  throw new Error(`UpdateKindMap not found in ${UPDATES_PATH}`)
}

const body = mapMatch[1] ?? ''

const entries: [string, string][] = []

for (const line of body.split('\n')) {
  const m = /^\s*"([^"]+)":\s*([A-Z][A-Za-z0-9]+);/.exec(line)

  if (m?.[1] && m[2]) {
    entries.push([m[1], m[2]])
  }
}

if (entries.length === 0) {
  throw new Error(`no entries parsed from UpdateKindMap in ${UPDATES_PATH}`)
}

// sanity: every curated kind must exist in @puregram/api
const found = new Set(entries.map(([k]) => k))
const missing = [...SESSION_AUGMENTED_KINDS].filter(k => !found.has(k))

if (missing.length > 0) {
  throw new Error(
    `curated kinds missing from @puregram/api UpdateKindMap (drift?): ${missing.join(', ')}`
  )
}

const augmented = entries.filter(([kind]) => SESSION_AUGMENTED_KINDS.has(kind))

const lines = [
  '/// AUTO-GENERATED by scripts/emit-augmentations.ts — do not edit by hand',
  '/// regenerate via `yarn generate:augmentations` after @puregram/api version bumps',
  '',
  "import type { SessionContext } from '../types'",
  '',
  "declare module '@puregram/api' {",
  ...augmented.map(([, cls]) => `  interface ${cls} { session: SessionContext }`),
  '}',
  '',
  'export {}',
  ''
]

await mkdir(dirname(OUT_PATH), { recursive: true })
await writeFile(OUT_PATH, lines.join('\n'), 'utf8')

console.log(`emitted ${augmented.length} augmentations → ${OUT_PATH}`)
