// objects that get wrapper classes — those that appear inside update payloads or as
// method return values where ergonomic access matters. keep alphabetical for clean diffs
export const WRAPPED_STRUCTURES = [
  'Animation',
  'Audio',
  'Chat',
  'ChatBoost',
  'ChatBoostRemoved',
  'ChatBoostSource',
  'ChatBoostUpdated',
  'ChatInviteLink',
  'ChatJoinRequest',
  'ChatLocation',
  'ChatMember',
  'ChatMemberUpdated',
  'ChatPermissions',
  'ChatPhoto',
  'ChatShared',
  'ChosenInlineResult',
  'Contact',
  'Dice',
  'Document',
  'ExternalReplyInfo',
  'File',
  'ForumTopicCreated',
  'ForumTopicEdited',
  'ForwardedMessage',
  'Game',
  'Giveaway',
  'GiveawayCompleted',
  'GiveawayWinners',
  'InlineKeyboardButton',
  'InlineKeyboardMarkup',
  'InlineQuery',
  'Invoice',
  'LinkPreviewOptions',
  'Location',
  'MaskPosition',
  'Message',
  'MessageEntity',
  'MessageId',
  'MessageOrigin',
  'MessageReactionCountUpdated',
  'MessageReactionUpdated',
  'OrderInfo',
  'PassportData',
  'PhotoSize',
  'Poll',
  'PollAnswer',
  'PollOption',
  'PreCheckoutQuery',
  'ProximityAlertTriggered',
  'ReactionCount',
  'ShippingAddress',
  'ShippingQuery',
  'Sticker',
  'StickerSet',
  'Story',
  'SuccessfulPayment',
  'TextQuote',
  'User',
  'UserProfilePhotos',
  'UsersShared',
  'Venue',
  'Video',
  'VideoChatEnded',
  'VideoChatParticipantsInvited',
  'VideoChatScheduled',
  'VideoNote',
  'Voice',
  'WebAppData',
  'WebAppInfo',
  'WriteAccessAllowed'
] as const

export type WrappedStructureName = typeof WRAPPED_STRUCTURES[number]

export function isWrappedStructure (name: string) {
  return (WRAPPED_STRUCTURES as readonly string[]).includes(name)
}
