// emit-augmentations.ts — codegen for src/generated/augmentations.ts
//
// reads Object.keys(EXTRACTORS) from src/augment/extractors.ts as the source of truth,
// looks up each kind's update class name from @puregram/api/src/generated/updates.ts,
// and emits one `declare module '@puregram/api' { interface XUpdate { flow: UpdateFlowExtension } }`
// block per entry. one source of truth: the EXTRACTORS map. types follow.
//
// regenerate via `yarn generate:augmentations` after:
//   - adding/removing an EXTRACTORS entry
//   - a @puregram/api version bump (UpdateKindMap may have renamed classes)

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { EXTRACTORS } from '../src/augment/extractors'

const here = dirname(fileURLToPath(import.meta.url))
const UPDATES_PATH = resolve(here, '../../api/src/generated/updates.ts')
const OUT_PATH = resolve(here, '../src/generated/augmentations.ts')

const text = await readFile(UPDATES_PATH, 'utf8')
const mapMatch = /export interface UpdateKindMap \{([\s\S]*?)\}/.exec(text)

if (!mapMatch) {
  throw new Error(`UpdateKindMap not found in ${UPDATES_PATH}`)
}

const body = mapMatch[1] ?? ''
const kindToClass = new Map<string, string>()

for (const line of body.split('\n')) {
  const m = /^\s*"([^"]+)":\s*([A-Z][A-Za-z0-9]+);/.exec(line)

  if (m?.[1] !== undefined && m[2] !== undefined) {
    kindToClass.set(m[1], m[2])
  }
}

if (kindToClass.size === 0) {
  throw new Error(`no entries parsed from UpdateKindMap in ${UPDATES_PATH}`)
}

const augmented: [string, string][] = []
const missing: string[] = []

for (const kind of Object.keys(EXTRACTORS)) {
  const cls = kindToClass.get(kind)

  if (cls === undefined) {
    missing.push(kind)
    continue
  }

  augmented.push([kind, cls])
}

if (missing.length > 0) {
  throw new Error(
    `EXTRACTORS keys missing from @puregram/api UpdateKindMap (drift?): ${missing.join(', ')}`
  )
}

augmented.sort((a, b) => a[1].localeCompare(b[1]))

const lines = [
  '/* eslint-disable -- AUTO-GENERATED file; run `yarn generate:augmentations` to regenerate */',
  '/// AUTO-GENERATED by scripts/emit-augmentations.ts — do not edit by hand',
  '/// regenerate via `yarn generate:augmentations` after EXTRACTORS edits or @puregram/api version bumps',
  '',
  "import type { UpdateFlowExtension } from '../augment/types'",
  '',
  "declare module '@puregram/api' {",
  ...augmented.map(([, cls]) => `  interface ${cls} { flow: UpdateFlowExtension }`),
  '}',
  '',
  'export {}',
  ''
]

await mkdir(dirname(OUT_PATH), { recursive: true })
await writeFile(OUT_PATH, lines.join('\n'), 'utf8')

console.log(`emitted ${augmented.length} augmentations → ${OUT_PATH}`)
